apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-platform-deployment
  namespace: donation-platform
  labels:
    app: donation-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: donation-application

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: donation-application

    spec:
      containers:
        - name: donation-platform-container
          image: ghcr.io/jazibeqbal/donation-application:8fbd6e14ab722d63700618e253871856a66605df
          ports:
            - containerPort: 8000
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: donation-platform-config

            - secretRef:
                name: donation-platform-secret

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
