apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-platform-deployment
  namespace: donation-platform
  labels:
    app: donation-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: donation-application

  template:
    metadata:
      labels:
        app: donation-application

    spec:
      containers:
        - name: donation-platform-container
          image: donation-platform:1.0
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: donation-platform-config

            - secretRef:
                name: donation-platform-secret

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20