apiVersion: v1
kind: Pod
metadata:
  name: donation-platform-pod
  labels:
    app: donation-application
spec:
  containers:
    - name: donation-application-container
      image: donation-platform:1.0
      ports:
        - containerPort: 8080