apiVersion: v1
kind: Service
metadata:
  name: donation-platform-service
  namespace: donation-platform
spec:
  selector:
    app: donation-application
  type: NodePort
  ports:
    - port: 8000 # port exposed by the Kubernetes Service
      targetPort: 8000 # port where container is listening